/* Query 1.  Business Scenario

The Sales Manager wants to identify the top-performing customers in every country.

Business Requirement

Write a SQL query to:

Calculate the total revenue generated by every customer.
Calculate the total number of orders placed by every customer.
Calculate the average order value for every customer.
Rank customers within each country based on total revenue.
Return only the top 3 customers from every country.*/

WITH top_customers AS
(
    SELECT
        c.customer_id,
        c.customer_name,
        c.country,

        SUM(f.sales_revenue) AS total_revenue,

        COUNT(DISTINCT f.order_id) AS total_orders,

        ROUND(
            SUM(f.sales_revenue) * 1.0
            /
            COUNT(DISTINCT f.order_id),
            2
        ) AS average_order_value

    FROM fact_sales f

    JOIN dim_customers c
        ON f.customer_id = c.customer_id

    GROUP BY
        c.customer_id,
        c.customer_name,
        c.country
),

ranked_customers AS
(
    SELECT
        *,

        ROW_NUMBER() OVER
        (
            PARTITION BY country
            ORDER BY total_revenue DESC
        ) AS rn

    FROM top_customers
)

SELECT *

FROM ranked_customers

WHERE rn <= 3;



/* Query 2. Business Scenario

The Regional Sales Manager wants to identify the best-performing stores in each country.

Business Requirement

Write a SQL query to:

Calculate the total sales revenue generated by every store.
Calculate the total number of orders handled by every store.
Calculate the average order value for every store.
Calculate each store's percentage contribution to its country's total revenue.
Rank stores within each country based on total revenue.
Return only the top 2 stores from each country.*/

-- Step 1 : Calculate Store Metrics

WITH store_metrics AS
(
    SELECT
        s.store_id,
        s.store_name,
        s.country,

        SUM(f.sales_revenue) AS total_revenue,

        COUNT(DISTINCT f.order_id) AS total_orders,

        ROUND
        (
            SUM(f.sales_revenue) * 1.0
            /
            COUNT(DISTINCT f.order_id),
            2
        ) AS average_order_value

    FROM fact_sales f

    JOIN dim_stores s
        ON f.store_id = s.store_id

    GROUP BY
        s.store_id,
        s.store_name,
        s.country
),

-- Step 2 : Calculate Country Revenue,
-- Revenue Contribution and Rank

ranked_store AS
(
    SELECT
        *,

        SUM(total_revenue) OVER
        (
            PARTITION BY country
        ) AS country_total_revenue,

        ROUND
        (
            total_revenue * 100.0
            /
            SUM(total_revenue) OVER
            (
                PARTITION BY country
            ),
            2
        ) AS revenue_contribution_pct,

        ROW_NUMBER() OVER
        (
            PARTITION BY country
            ORDER BY total_revenue DESC
        ) AS rn

    FROM store_metrics
)

SELECT
    store_id,
    store_name,
    country,
    total_revenue,
    total_orders,
    average_order_value,
    country_total_revenue,
    revenue_contribution_pct,
    rn

FROM ranked_store

WHERE rn <= 2

ORDER BY
    country,
    rn;

/* Query 3. Business Scenario

The Marketing team wants to identify the most valuable product categories in each country.

Business Requirement

Write a SQL query to:

Calculate the total sales revenue for every product category in each country.
Calculate the total quantity sold for every category.
Calculate the average selling price for each category.
Calculate the percentage contribution of each category to its country's total revenue.
Rank categories within each country based on total revenue.
Return only the top 3 product categories from each country.*/

WITH top_product_category AS
(
    SELECT
        country,
        p.category,

        SUM(f.sales_amount) AS total_revenue,

        SUM(f.quantity_sold) AS total_quantity,

        ROUND(
            SUM(f.sales_amount) * 1.0
            /
            SUM(f.quantity_sold),
            2
        ) AS average_selling_price

    FROM fact_sales f

    JOIN dim_products p
        ON f.product_id = p.product_id

    GROUP BY
        country,
        p.category
),

percentage_contribution AS
(
    SELECT
        *,

        SUM(total_revenue) OVER
        (
            PARTITION BY country
        ) AS country_total_revenue,

        ROUND
        (
            total_revenue * 100.0
            /
            SUM(total_revenue) OVER
            (
                PARTITION BY country
            ),
            2
        ) AS revenue_contribution

    FROM top_product_category
),

ranked_country AS
(
    SELECT
        *,

        ROW_NUMBER() OVER
        (
            PARTITION BY country
            ORDER BY total_revenue DESC
        ) AS rn

    FROM percentage_contribution
)

SELECT *

FROM ranked_country

WHERE rn <= 3;
