/* Query 1.  Business Scenario

The Sales Manager wants to identify the top-performing customers in every country.

Business Requirement

Write a SQL query to:

Calculate the total revenue generated by every customer.
Calculate the total number of orders placed by every customer.
Calculate the average order value for every customer.
Rank customers within each country based on total revenue.
Return only the top 3 customers from every country.*/

WITH top_customers AS
(
    SELECT
        c.customer_id,
        c.customer_name,
        c.country,

        SUM(f.sales_revenue) AS total_revenue,

        COUNT(DISTINCT f.order_id) AS total_orders,

        ROUND(
            SUM(f.sales_revenue) * 1.0
            /
            COUNT(DISTINCT f.order_id),
            2
        ) AS average_order_value

    FROM fact_sales f

    JOIN dim_customers c
        ON f.customer_id = c.customer_id

    GROUP BY
        c.customer_id,
        c.customer_name,
        c.country
),

ranked_customers AS
(
    SELECT
        *,

        ROW_NUMBER() OVER
        (
            PARTITION BY country
            ORDER BY total_revenue DESC
        ) AS rn

    FROM top_customers
)

SELECT *

FROM ranked_customers

WHERE rn <= 3;



/* Query 2. Business Scenario

The Regional Sales Manager wants to identify the best-performing stores in each country.

Business Requirement

Write a SQL query to:

Calculate the total sales revenue generated by every store.
Calculate the total number of orders handled by every store.
Calculate the average order value for every store.
Calculate each store's percentage contribution to its country's total revenue.
Rank stores within each country based on total revenue.
Return only the top 2 stores from each country.*/

-- Step 1 : Calculate Store Metrics

WITH store_metrics AS
(
    SELECT
        s.store_id,
        s.store_name,
        s.country,

        SUM(f.sales_revenue) AS total_revenue,

        COUNT(DISTINCT f.order_id) AS total_orders,

        ROUND
        (
            SUM(f.sales_revenue) * 1.0
            /
            COUNT(DISTINCT f.order_id),
            2
        ) AS average_order_value

    FROM fact_sales f

    JOIN dim_stores s
        ON f.store_id = s.store_id

    GROUP BY
        s.store_id,
        s.store_name,
        s.country
),

-- Step 2 : Calculate Country Revenue,
-- Revenue Contribution and Rank

ranked_store AS
(
    SELECT
        *,

        SUM(total_revenue) OVER
        (
            PARTITION BY country
        ) AS country_total_revenue,

        ROUND
        (
            total_revenue * 100.0
            /
            SUM(total_revenue) OVER
            (
                PARTITION BY country
            ),
            2
        ) AS revenue_contribution_pct,

        ROW_NUMBER() OVER
        (
            PARTITION BY country
            ORDER BY total_revenue DESC
        ) AS rn

    FROM store_metrics
)

SELECT
    store_id,
    store_name,
    country,
    total_revenue,
    total_orders,
    average_order_value,
    country_total_revenue,
    revenue_contribution_pct,
    rn

FROM ranked_store

WHERE rn <= 2

ORDER BY
    country,
    rn;

/* Query 3. Business Scenario

The Marketing team wants to identify the most valuable product categories in each country.

Business Requirement

Write a SQL query to:

Calculate the total sales revenue for every product category in each country.
Calculate the total quantity sold for every category.
Calculate the average selling price for each category.
Calculate the percentage contribution of each category to its country's total revenue.
Rank categories within each country based on total revenue.
Return only the top 3 product categories from each country.*/

WITH top_product_category AS
(
    SELECT
        country,
        p.category,

        SUM(f.sales_amount) AS total_revenue,

        SUM(f.quantity_sold) AS total_quantity,

        ROUND(
            SUM(f.sales_amount) * 1.0
            /
            SUM(f.quantity_sold),
            2
        ) AS average_selling_price

    FROM fact_sales f

    JOIN dim_products p
        ON f.product_id = p.product_id

    GROUP BY
        country,
        p.category
),

percentage_contribution AS
(
    SELECT
        *,

        SUM(total_revenue) OVER
        (
            PARTITION BY country
        ) AS country_total_revenue,

        ROUND
        (
            total_revenue * 100.0
            /
            SUM(total_revenue) OVER
            (
                PARTITION BY country
            ),
            2
        ) AS revenue_contribution

    FROM top_product_category
),

ranked_country AS
(
    SELECT
        *,

        ROW_NUMBER() OVER
        (
            PARTITION BY country
            ORDER BY total_revenue DESC
        ) AS rn

    FROM percentage_contribution
)

SELECT *

FROM ranked_country

WHERE rn <= 3;


/* Query 4. Business Scenario

The Finance team wants to analyze customer purchasing trends over time.

Business Requirement

Write a SQL query to:

Calculate each customer's monthly revenue.
Calculate the previous month's revenue for each customer.
Calculate the month-over-month (MoM) growth percentage.
Calculate the company's average monthly customer revenue for the same month.
Compare each customer's monthly revenue against the company average.
Rank customers within each month based on monthly revenue.
Return the top 5 customers for every month.*/

-- Step 1 : Calculate Monthly Revenue for every Customer

WITH monthly_revenue AS
(
    SELECT
        c.customer_id,
        c.customer_name,

        DATE_TRUNC('month',f.order_date) AS order_month,

        SUM(f.sales_revenue) AS monthly_revenue

    FROM fact_sales f

    JOIN dim_customers c
        ON f.customer_id = c.customer_id

    GROUP BY
        c.customer_id,
        c.customer_name,
        DATE_TRUNC('month',f.order_date)
),

-- Step 2 : Previous Month Revenue,
-- Company Average Revenue and MoM Growth

customer_metrics AS
(
    SELECT
        *,

        LAG(monthly_revenue) OVER
        (
            PARTITION BY customer_id
            ORDER BY order_month
        ) AS previous_month_revenue,

        AVG(monthly_revenue) OVER
        (
            PARTITION BY order_month
        ) AS company_monthly_average

    FROM monthly_revenue
),

-- Step 3 : Calculate Growth and Rank Customers

ranked_customers AS
(
    SELECT
        *,

        ROUND
        (
            (
                monthly_revenue
                -
                previous_month_revenue
            )
            *100.0
            /
            NULLIF(previous_month_revenue,0),
            2
        ) AS mom_growth_percent,

        ROUND
        (
            (
                monthly_revenue
                -
                company_monthly_average
            )
            *100.0
            /
            NULLIF(company_monthly_average,0),
            2
        ) AS revenue_vs_company_percent,

        ROW_NUMBER() OVER
        (
            PARTITION BY order_month
            ORDER BY monthly_revenue DESC
        ) AS rn

    FROM customer_metrics
)

SELECT
    customer_id,
    customer_name,
    order_month,
    monthly_revenue,
    previous_month_revenue,
    mom_growth_percent,
    company_monthly_average,
    revenue_vs_company_percent,
    rn

FROM ranked_customers

WHERE rn <= 5

ORDER BY
    order_month,
    rn;


/*Business Scenario

The Sales Director wants to identify the best-performing sales employees across different countries.

Business Requirement

Write a SQL query to:

Calculate each employee's total yearly revenue.
Calculate the total number of orders handled by each employee.
Calculate the average order value for each employee.
Calculate the previous year's revenue using a window function.
Calculate the Year-over-Year (YoY) Growth %.
Calculate the company average employee revenue for the same year.
Calculate each employee's percentage difference compared to the company average.
Rank employees within each country based on yearly revenue.
Return only the top 3 employees from each country.*/

-- Step 1 : Calculate Employee Yearly Metrics

WITH employee_metrics AS
(
    SELECT
        e.employee_id,
        e.employee_name,
        e.country,

        EXTRACT(YEAR FROM f.order_date) AS sales_year,

        SUM(f.sales_revenue) AS yearly_revenue,

        COUNT(DISTINCT f.order_id) AS total_orders,

        ROUND
        (
            SUM(f.sales_revenue) * 1.0
            /
            COUNT(DISTINCT f.order_id),
            2
        ) AS average_order_value

    FROM fact_sales f

    JOIN dim_employees e
        ON f.employee_id = e.employee_id

    GROUP BY
        e.employee_id,
        e.employee_name,
        e.country,
        EXTRACT(YEAR FROM f.order_date)
),

-- Step 2 : Calculate Previous Year Revenue,
-- Company Average Revenue,
-- YoY Growth and Company Comparison

employee_growth AS
(
    SELECT
        *,

        LAG(yearly_revenue) OVER
        (
            PARTITION BY employee_id
            ORDER BY sales_year
        ) AS previous_year_revenue,

        AVG(yearly_revenue) OVER
        (
            PARTITION BY sales_year
        ) AS company_yearly_average

    FROM employee_metrics
),

-- Step 3 : Rank Employees

ranked_employees AS
(
    SELECT
        *,

        ROUND
        (
            (
                yearly_revenue
                -
                previous_year_revenue
            )
            *100.0
            /
            NULLIF(previous_year_revenue,0),
            2
        ) AS yoy_growth_percent,

        ROUND
        (
            (
                yearly_revenue
                -
                company_yearly_average
            )
            *100.0
            /
            NULLIF(company_yearly_average,0),
            2
        ) AS revenue_vs_company_percent,

        ROW_NUMBER() OVER
        (
            PARTITION BY country
            ORDER BY yearly_revenue DESC
        ) AS rn

    FROM employee_growth
)

SELECT
    employee_id,
    employee_name,
    country,
    sales_year,
    yearly_revenue,
    total_orders,
    average_order_value,
    previous_year_revenue,
    yoy_growth_percent,
    company_yearly_average,
    revenue_vs_company_percent,
    rn

FROM ranked_employees

WHERE rn <= 3

ORDER BY
    country,
    rn;
